"""Realistic mock hotel database for prototype."""
from __future__ import annotations

DESTINATIONS: list[dict] = [
    # ── domestic ──
    {"name": "서울", "name_en": "Seoul", "category": "domestic", "country": "한국", "popular": True},
    {"name": "부산", "name_en": "Busan", "category": "domestic", "country": "한국", "popular": True},
    {"name": "제주", "name_en": "Jeju", "category": "domestic", "country": "한국", "popular": True},
    {"name": "강릉", "name_en": "Gangneung", "category": "domestic", "country": "한국", "popular": True},
    {"name": "경주", "name_en": "Gyeongju", "category": "domestic", "country": "한국", "popular": True},
    {"name": "여수", "name_en": "Yeosu", "category": "domestic", "country": "한국", "popular": True},
    {"name": "속초", "name_en": "Sokcho", "category": "domestic", "country": "한국"},
    {"name": "전주", "name_en": "Jeonju", "category": "domestic", "country": "한국"},
    {"name": "대구", "name_en": "Daegu", "category": "domestic", "country": "한국"},
    {"name": "인천", "name_en": "Incheon", "category": "domestic", "country": "한국"},
    {"name": "광주", "name_en": "Gwangju", "category": "domestic", "country": "한국"},
    {"name": "대전", "name_en": "Daejeon", "category": "domestic", "country": "한국"},
    {"name": "울산", "name_en": "Ulsan", "category": "domestic", "country": "한국"},
    {"name": "수원", "name_en": "Suwon", "category": "domestic", "country": "한국"},
    {"name": "춘천", "name_en": "Chuncheon", "category": "domestic", "country": "한국"},
    {"name": "가평", "name_en": "Gapyeong", "category": "domestic", "country": "한국"},
    {"name": "양양", "name_en": "Yangyang", "category": "domestic", "country": "한국"},
    {"name": "통영", "name_en": "Tongyeong", "category": "domestic", "country": "한국"},
    {"name": "거제", "name_en": "Geoje", "category": "domestic", "country": "한국"},
    {"name": "남해", "name_en": "Namhae", "category": "domestic", "country": "한국"},
    {"name": "목포", "name_en": "Mokpo", "category": "domestic", "country": "한국"},
    {"name": "안동", "name_en": "Andong", "category": "domestic", "country": "한국"},
    {"name": "포항", "name_en": "Pohang", "category": "domestic", "country": "한국"},
    {"name": "순천", "name_en": "Suncheon", "category": "domestic", "country": "한국"},
    {"name": "평창", "name_en": "Pyeongchang", "category": "domestic", "country": "한국"},
    {"name": "담양", "name_en": "Damyang", "category": "domestic", "country": "한국"},
    # ── international ──
    {"name": "도쿄", "name_en": "Tokyo", "category": "international", "country": "일본", "popular": True},
    {"name": "오사카", "name_en": "Osaka", "category": "international", "country": "일본", "popular": True},
    {"name": "방콕", "name_en": "Bangkok", "category": "international", "country": "태국", "popular": True},
    {"name": "다낭", "name_en": "Da Nang", "category": "international", "country": "베트남", "popular": True},
    {"name": "싱가포르", "name_en": "Singapore", "category": "international", "country": "싱가포르"},
    {"name": "하와이", "name_en": "Hawaii", "category": "international", "country": "미국"},
    {"name": "파리", "name_en": "Paris", "category": "international", "country": "프랑스"},
    {"name": "런던", "name_en": "London", "category": "international", "country": "영국"},
    {"name": "뉴욕", "name_en": "New York", "category": "international", "country": "미국"},
    {"name": "세부", "name_en": "Cebu", "category": "international", "country": "필리핀"},
    {"name": "발리", "name_en": "Bali", "category": "international", "country": "인도네시아"},
    {"name": "후쿠오카", "name_en": "Fukuoka", "category": "international", "country": "일본"},
    {"name": "타이베이", "name_en": "Taipei", "category": "international", "country": "대만"},
    {"name": "홍콩", "name_en": "Hong Kong", "category": "international", "country": "홍콩"},
]

HOTELS: list[dict] = [
    # ══════════════════════════════════════════════
    #  국내 (Domestic)
    # ══════════════════════════════════════════════

    # ── 서울 ──
    {"id": "SEL001", "name": "롯데호텔 서울", "destination": "서울", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.6, "review_count": 12840,
     "address": "서울 중구 을지로 30", "description": "서울 중심부 5성급 럭셔리 호텔",
     "amenities": ["수영장", "피트니스", "스파", "레스토랑", "주차"],
     "base_price": 280000, "image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=480&h=320&fit=crop"},
    {"id": "SEL002", "name": "신라호텔", "destination": "서울", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.7, "review_count": 9560,
     "address": "서울 중구 동호로 249", "description": "한국 최고의 전통 럭셔리 호텔",
     "amenities": ["수영장", "피트니스", "스파", "레스토랑", "면세점"],
     "base_price": 350000, "image": "https://images.unsplash.com/photo-1455587734955-081b22074882?w=480&h=320&fit=crop"},
    {"id": "SEL003", "name": "포시즌스 호텔 서울", "destination": "서울", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.8, "review_count": 5420,
     "address": "서울 종로구 새문안로 97", "description": "광화문 위치 최고급 호텔",
     "amenities": ["수영장", "피트니스", "스파", "레스토랑", "바"],
     "base_price": 450000, "image": "https://images.unsplash.com/photo-1561501900-3701fa6a0864?w=480&h=320&fit=crop"},
    {"id": "SEL004", "name": "나인트리 프리미어 명동", "destination": "서울", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 18320,
     "address": "서울 중구 마른내로 28", "description": "명동 쇼핑가 도보 3분 가성비 호텔",
     "amenities": ["피트니스", "레스토랑", "주차", "세탁"],
     "base_price": 120000, "image": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=480&h=320&fit=crop"},
    {"id": "SEL005", "name": "스테이 호텔 강남", "destination": "서울", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.0, "review_count": 7650,
     "address": "서울 강남구 테헤란로 134", "description": "강남역 5분, 비즈니스 호텔",
     "amenities": ["피트니스", "카페", "주차", "회의실"],
     "base_price": 95000, "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=480&h=320&fit=crop"},
    {"id": "SEL006", "name": "호텔 그레이스리 서울 명동", "destination": "서울", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.3, "review_count": 6210,
     "address": "서울 중구 퇴계로 128", "description": "일본 체인 감성 호텔, 명동 위치",
     "amenities": ["레스토랑", "카페", "세탁"],
     "base_price": 135000, "image": "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=480&h=320&fit=crop"},
    {"id": "SEL007", "name": "JW 메리어트 동대문 스퀘어", "destination": "서울", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.6, "review_count": 8430,
     "address": "서울 종로구 청계천로 279", "description": "동대문 DDP 옆 프리미엄 호텔",
     "amenities": ["수영장", "피트니스", "스파", "레스토랑", "주차"],
     "base_price": 310000, "image": "https://images.unsplash.com/photo-1542314831-de9b0a31f609?w=480&h=320&fit=crop"},
    {"id": "SEL008", "name": "글래드 마포", "destination": "서울", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 5670,
     "address": "서울 마포구 마포대로 92", "description": "공덕역 직결 모던 비즈니스 호텔",
     "amenities": ["피트니스", "레스토랑", "주차"],
     "base_price": 105000, "image": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=480&h=320&fit=crop"},

    # ── 부산 ──
    {"id": "BUS001", "name": "파라다이스호텔 부산", "destination": "부산", "category": "domestic",
     "hotel_type": "resort", "rating": 4.5, "review_count": 11200,
     "address": "부산 해운대구 해운대해변로 296", "description": "해운대 오션뷰 대표 리조트",
     "amenities": ["수영장", "카지노", "스파", "레스토랑", "해변"],
     "base_price": 300000, "image": "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=480&h=320&fit=crop"},
    {"id": "BUS002", "name": "시그니엘 부산", "destination": "부산", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.7, "review_count": 4820,
     "address": "부산 해운대구 달맞이길 30", "description": "LCT 타워 초고층 럭셔리 호텔",
     "amenities": ["수영장", "피트니스", "스파", "레스토랑", "오션뷰"],
     "base_price": 380000, "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=480&h=320&fit=crop"},
    {"id": "BUS003", "name": "해운대그랜드호텔", "destination": "부산", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 15600,
     "address": "부산 해운대구 해운대해변로 217", "description": "해운대 해변 바로 앞 전통 호텔",
     "amenities": ["수영장", "피트니스", "레스토랑", "주차"],
     "base_price": 180000, "image": "https://images.unsplash.com/photo-1537572263959-54ac5b117d17?w=480&h=320&fit=crop"},
    {"id": "BUS004", "name": "호메르스 호텔", "destination": "부산", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.3, "review_count": 8930,
     "address": "부산 해운대구 해운대로 570번길 46", "description": "감성 부티크 호텔",
     "amenities": ["레스토랑", "카페", "루프탑", "주차"],
     "base_price": 150000, "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=480&h=320&fit=crop"},
    {"id": "BUS005", "name": "힐튼 부산", "destination": "부산", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.4, "review_count": 6340,
     "address": "부산 기장군 기장읍 기장해안로 268-32", "description": "기장 해변 힐튼 리조트",
     "amenities": ["수영장", "스파", "해변", "레스토랑", "키즈존"],
     "base_price": 250000, "image": "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=480&h=320&fit=crop"},

    # ── 제주 ──
    {"id": "JEJ001", "name": "롯데호텔 제주", "destination": "제주", "category": "domestic",
     "hotel_type": "resort", "rating": 4.4, "review_count": 13500,
     "address": "제주 서귀포시 중문관광로 72번길 35", "description": "중문단지 대표 리조트",
     "amenities": ["수영장", "골프", "스파", "레스토랑", "키즈존"],
     "base_price": 250000, "image": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=480&h=320&fit=crop"},
    {"id": "JEJ002", "name": "해비치호텔 앤 리조트", "destination": "제주", "category": "domestic",
     "hotel_type": "resort", "rating": 4.5, "review_count": 9870,
     "address": "제주 서귀포시 표선면 민속해안로 537", "description": "한화 프리미엄 리조트",
     "amenities": ["수영장", "피트니스", "스파", "레스토랑", "자전거"],
     "base_price": 220000, "image": "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=480&h=320&fit=crop"},
    {"id": "JEJ003", "name": "제주신라호텔", "destination": "제주", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.6, "review_count": 7640,
     "address": "제주 서귀포시 중문관광로 72번길 75", "description": "중문단지 5성급 호텔",
     "amenities": ["수영장", "스파", "골프", "레스토랑", "해변"],
     "base_price": 320000, "image": "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=480&h=320&fit=crop"},
    {"id": "JEJ004", "name": "제주 탐나라 리퍼블릭", "destination": "제주", "category": "domestic",
     "hotel_type": "pension", "rating": 4.1, "review_count": 3210,
     "address": "제주 제주시 탑동로 2길 8", "description": "감성 독채 펜션",
     "amenities": ["바베큐", "주차", "정원", "와이파이"],
     "base_price": 85000, "image": "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=480&h=320&fit=crop"},
    {"id": "JEJ005", "name": "그랜드 하얏트 제주", "destination": "제주", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.7, "review_count": 3890,
     "address": "제주 제주시 노형동 925", "description": "제주 신시가지 최신 럭셔리 호텔",
     "amenities": ["수영장", "피트니스", "스파", "레스토랑", "바"],
     "base_price": 400000, "image": "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=480&h=320&fit=crop"},
    {"id": "JEJ006", "name": "플레이스캠프 제주", "destination": "제주", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 5640,
     "address": "제주 제주시 탑동해안로 66", "description": "제주항 근처 힙한 디자인 호텔",
     "amenities": ["카페", "루프탑", "자전거", "주차"],
     "base_price": 110000, "image": "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=480&h=320&fit=crop"},

    # ── 강릉 ──
    {"id": "GAN001", "name": "씨마크호텔 강릉", "destination": "강릉", "category": "domestic",
     "hotel_type": "resort", "rating": 4.4, "review_count": 6540,
     "address": "강원 강릉시 해안로 406번길 2", "description": "강릉 대표 오션뷰 리조트",
     "amenities": ["수영장", "스파", "레스토랑", "해변", "워터파크"],
     "base_price": 200000, "image": "https://images.unsplash.com/photo-1544124499-58912cbddaad?w=480&h=320&fit=crop"},
    {"id": "GAN002", "name": "세인트존스호텔 강릉", "destination": "강릉", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 5120,
     "address": "강원 강릉시 창해로 307", "description": "경포대 근처 비즈니스 겸 리조트",
     "amenities": ["피트니스", "레스토랑", "주차", "해변"],
     "base_price": 160000, "image": "https://images.unsplash.com/photo-1559599238-308793637427?w=480&h=320&fit=crop"},
    {"id": "GAN003", "name": "스카이베이 경포", "destination": "강릉", "category": "domestic",
     "hotel_type": "resort", "rating": 4.3, "review_count": 7890,
     "address": "강원 강릉시 해안로 514", "description": "경포해변 앞 워터파크 리조트",
     "amenities": ["워터파크", "수영장", "키즈존", "레스토랑"],
     "base_price": 180000, "image": "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?w=480&h=320&fit=crop"},

    # ── 경주 ──
    {"id": "GYE001", "name": "힐튼 경주", "destination": "경주", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.3, "review_count": 8760,
     "address": "경북 경주시 보문로 484-7", "description": "보문단지 내 국제 체인 호텔",
     "amenities": ["수영장", "피트니스", "골프", "레스토랑"],
     "base_price": 170000, "image": "https://images.unsplash.com/photo-1549294413-26f195471e71?w=480&h=320&fit=crop"},
    {"id": "GYE002", "name": "코모도호텔 경주", "destination": "경주", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.0, "review_count": 5430,
     "address": "경북 경주시 보문로 422", "description": "보문호수 전망 리조트형 호텔",
     "amenities": ["수영장", "피트니스", "레스토랑", "자전거"],
     "base_price": 130000, "image": "https://images.unsplash.com/photo-1551016043-93ae65f4c88c?w=480&h=320&fit=crop"},
    {"id": "GYE003", "name": "경주 라한호텔", "destination": "경주", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 4320,
     "address": "경북 경주시 보문로 338", "description": "보문단지 가성비 리조트",
     "amenities": ["수영장", "레스토랑", "주차", "자전거"],
     "base_price": 110000, "image": "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=480&h=320&fit=crop"},

    # ── 여수 ──
    {"id": "YEO001", "name": "디오션리조트 여수", "destination": "여수", "category": "domestic",
     "hotel_type": "resort", "rating": 4.3, "review_count": 7890,
     "address": "전남 여수시 오동도로 61-11", "description": "오동도 근처 오션뷰 리조트",
     "amenities": ["수영장", "스파", "레스토랑", "오션뷰"],
     "base_price": 190000, "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=480&h=320&fit=crop"},
    {"id": "YEO002", "name": "히든베이호텔 여수", "destination": "여수", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.4, "review_count": 5640,
     "address": "전남 여수시 돌산읍 무술목길 142", "description": "돌산 바다 뷰 프리미엄 호텔",
     "amenities": ["수영장", "레스토랑", "오션뷰", "주차"],
     "base_price": 220000, "image": "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=480&h=320&fit=crop"},
    {"id": "YEO003", "name": "MVL호텔 여수", "destination": "여수", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 6780,
     "address": "전남 여수시 오동도로 111", "description": "여수엑스포역 앞 비즈니스 호텔",
     "amenities": ["피트니스", "레스토랑", "주차", "카페"],
     "base_price": 120000, "image": "https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=480&h=320&fit=crop"},

    # ── 속초 ──
    {"id": "SOK001", "name": "마리나베이 속초", "destination": "속초", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 4560,
     "address": "강원 속초시 중앙로 118", "description": "속초 해변 앞 모던 호텔",
     "amenities": ["피트니스", "레스토랑", "오션뷰", "주차"],
     "base_price": 140000, "image": "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=480&h=320&fit=crop"},
    {"id": "SOK002", "name": "롯데리조트 속초", "destination": "속초", "category": "domestic",
     "hotel_type": "resort", "rating": 4.3, "review_count": 8900,
     "address": "강원 속초시 대포항길 186", "description": "설악산+동해 동시 전망 리조트",
     "amenities": ["수영장", "워터파크", "피트니스", "레스토랑"],
     "base_price": 180000, "image": "https://images.unsplash.com/photo-1585409677983-0f6c2e0b3ffd?w=480&h=320&fit=crop"},

    # ── 전주 ──
    {"id": "JNJ001", "name": "라한호텔 전주", "destination": "전주", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 5670,
     "address": "전북 전주시 완산구 기린대로 85", "description": "한옥마을 근처 프리미엄 호텔",
     "amenities": ["수영장", "피트니스", "레스토랑", "주차"],
     "base_price": 140000, "image": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=480&h=320&fit=crop&q=80&seed=jnj"},
    {"id": "JNJ002", "name": "전주 한옥 스테이", "destination": "전주", "category": "domestic",
     "hotel_type": "pension", "rating": 4.5, "review_count": 3210,
     "address": "전북 전주시 완산구 은행로 56", "description": "한옥마을 내 전통 한옥 숙소",
     "amenities": ["정원", "전통차", "주차", "와이파이"],
     "base_price": 95000, "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=480&h=320&fit=crop&q=80&seed=jnj2"},

    # ── 대구 ──
    {"id": "DGU001", "name": "인터불고 호텔 대구", "destination": "대구", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 6540,
     "address": "대구 수성구 팔현길 212", "description": "대구 최대 규모 호텔",
     "amenities": ["수영장", "골프", "피트니스", "레스토랑"],
     "base_price": 150000, "image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=480&h=320&fit=crop&q=80&seed=dgu"},
    {"id": "DGU002", "name": "노보텔 앰배서더 대구", "destination": "대구", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.3, "review_count": 4560,
     "address": "대구 중구 국채보상로 611", "description": "동성로 중심 비즈니스 호텔",
     "amenities": ["피트니스", "레스토랑", "주차", "회의실"],
     "base_price": 130000, "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=480&h=320&fit=crop&q=80&seed=dgu2"},

    # ── 인천 ──
    {"id": "ICN001", "name": "네스트호텔 인천", "destination": "인천", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 7890,
     "address": "인천 중구 영종해안남로 186", "description": "영종도 해변 리조트형 호텔",
     "amenities": ["수영장", "스파", "레스토랑", "해변"],
     "base_price": 170000, "image": "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=480&h=320&fit=crop&q=80&seed=icn"},
    {"id": "ICN002", "name": "파라다이스시티 인천", "destination": "인천", "category": "domestic",
     "hotel_type": "resort", "rating": 4.5, "review_count": 9120,
     "address": "인천 중구 영종해안남로 321대로 186", "description": "영종도 복합리조트, 카지노+스파",
     "amenities": ["수영장", "카지노", "스파", "레스토랑", "클럽"],
     "base_price": 300000, "image": "https://images.unsplash.com/photo-1455587734955-081b22074882?w=480&h=320&fit=crop&q=80&seed=icn2"},

    # ── 광주 ──
    {"id": "GWJ001", "name": "홀리데이인 광주", "destination": "광주", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 4320,
     "address": "광주 서구 상무중앙로 38", "description": "상무지구 중심 국제 체인 호텔",
     "amenities": ["피트니스", "레스토랑", "주차", "회의실"],
     "base_price": 120000, "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=480&h=320&fit=crop&q=80&seed=gwj"},

    # ── 대전 ──
    {"id": "DJN001", "name": "ICC호텔 대전", "destination": "대전", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.0, "review_count": 5430,
     "address": "대전 유성구 엑스포로 1", "description": "대전컨벤션센터 옆 비즈니스 호텔",
     "amenities": ["피트니스", "레스토랑", "주차", "회의실"],
     "base_price": 110000, "image": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=480&h=320&fit=crop&q=80&seed=djn"},
    {"id": "DJN002", "name": "유성호텔 대전", "destination": "대전", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 6780,
     "address": "대전 유성구 온천로 77", "description": "유성온천 프리미엄 온천 호텔",
     "amenities": ["온천", "스파", "레스토랑", "주차"],
     "base_price": 140000, "image": "https://images.unsplash.com/photo-1551016043-93ae65f4c88c?w=480&h=320&fit=crop&q=80&seed=djn2"},

    # ── 울산 ──
    {"id": "ULS001", "name": "롯데호텔 울산", "destination": "울산", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.3, "review_count": 5120,
     "address": "울산 남구 삼산로 282", "description": "울산 시내 중심 프리미엄 호텔",
     "amenities": ["피트니스", "레스토랑", "주차", "스파"],
     "base_price": 160000, "image": "https://images.unsplash.com/photo-1542314831-de9b0a31f609?w=480&h=320&fit=crop&q=80&seed=uls"},

    # ── 수원 ──
    {"id": "SWN001", "name": "노보텔 앰배서더 수원", "destination": "수원", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 4890,
     "address": "경기 수원시 팔달구 중부대로 141", "description": "수원역 앞 국제 체인 호텔",
     "amenities": ["피트니스", "레스토랑", "주차", "회의실"],
     "base_price": 130000, "image": "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=480&h=320&fit=crop&q=80&seed=swn"},

    # ── 춘천 ──
    {"id": "CCN001", "name": "세종호텔 춘천", "destination": "춘천", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.0, "review_count": 3450,
     "address": "강원 춘천시 봉의산길 31", "description": "춘천 시내 중심 호텔",
     "amenities": ["레스토랑", "주차", "카페"],
     "base_price": 90000, "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=480&h=320&fit=crop&q=80&seed=ccn"},
    {"id": "CCN002", "name": "엘리시안 강촌 리조트", "destination": "춘천", "category": "domestic",
     "hotel_type": "resort", "rating": 4.3, "review_count": 8760,
     "address": "강원 춘천시 남산면 북한강변길 688", "description": "강촌 스키+골프 종합 리조트",
     "amenities": ["스키", "골프", "수영장", "레스토랑"],
     "base_price": 160000, "image": "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=480&h=320&fit=crop&q=80&seed=ccn2"},

    # ── 가평 ──
    {"id": "GPY001", "name": "아난티 코브 가평", "destination": "가평", "category": "domestic",
     "hotel_type": "resort", "rating": 4.6, "review_count": 4560,
     "address": "경기 가평군 설악면 유명로 1720", "description": "북한강변 프리미엄 리조트",
     "amenities": ["수영장", "스파", "레스토랑", "골프", "카페"],
     "base_price": 280000, "image": "https://images.unsplash.com/photo-1561501900-3701fa6a0864?w=480&h=320&fit=crop&q=80&seed=gpy"},
    {"id": "GPY002", "name": "가평 숲속 펜션", "destination": "가평", "category": "domestic",
     "hotel_type": "pension", "rating": 4.2, "review_count": 2340,
     "address": "경기 가평군 청평면 고재길 42", "description": "자연 속 독채 펜션, 계곡 인접",
     "amenities": ["바베큐", "계곡", "정원", "주차"],
     "base_price": 75000, "image": "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=480&h=320&fit=crop&q=80&seed=gpy2"},

    # ── 양양 ──
    {"id": "YYG001", "name": "쏠비치 양양", "destination": "양양", "category": "domestic",
     "hotel_type": "resort", "rating": 4.3, "review_count": 7650,
     "address": "강원 양양군 손양면 동해대로 2623", "description": "동해 오션뷰 워터파크 리조트",
     "amenities": ["워터파크", "수영장", "해변", "레스토랑"],
     "base_price": 190000, "image": "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=480&h=320&fit=crop&q=80&seed=yyg"},
    {"id": "YYG002", "name": "서피비치 양양", "destination": "양양", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 5430,
     "address": "강원 양양군 현북면 하조대해안길 119", "description": "서핑 성지 해변 앞 호텔",
     "amenities": ["서핑", "해변", "카페", "주차"],
     "base_price": 120000, "image": "https://images.unsplash.com/photo-1537572263959-54ac5b117d17?w=480&h=320&fit=crop&q=80&seed=yyg2"},

    # ── 통영 ──
    {"id": "TYG001", "name": "스탠포드호텔 통영", "destination": "통영", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 4560,
     "address": "경남 통영시 도남로 257", "description": "한려수도 전망 호텔",
     "amenities": ["레스토랑", "카페", "주차", "오션뷰"],
     "base_price": 140000, "image": "https://images.unsplash.com/photo-1559599238-308793637427?w=480&h=320&fit=crop&q=80&seed=tyg"},
    {"id": "TYG002", "name": "통영 마리나 리조트", "destination": "통영", "category": "domestic",
     "hotel_type": "resort", "rating": 4.4, "review_count": 3890,
     "address": "경남 통영시 산양읍 산양관광로 1", "description": "요트 마리나 뷰 리조트",
     "amenities": ["수영장", "요트", "레스토랑", "해변"],
     "base_price": 200000, "image": "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?w=480&h=320&fit=crop&q=80&seed=tyg2"},

    # ── 거제 ──
    {"id": "GJE001", "name": "거제 삼성 리조트", "destination": "거제", "category": "domestic",
     "hotel_type": "resort", "rating": 4.3, "review_count": 6540,
     "address": "경남 거제시 거제대로 3731", "description": "거제도 남해바다 전망 리조트",
     "amenities": ["수영장", "골프", "레스토랑", "해변"],
     "base_price": 180000, "image": "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=480&h=320&fit=crop&q=80&seed=gje"},

    # ── 남해 ──
    {"id": "NMH001", "name": "힐튼남해 골프&리조트", "destination": "남해", "category": "domestic",
     "hotel_type": "resort", "rating": 4.4, "review_count": 5430,
     "address": "경남 남해군 남면 남해대로 958", "description": "남해 바다+골프 프리미엄 리조트",
     "amenities": ["골프", "수영장", "레스토랑", "오션뷰"],
     "base_price": 200000, "image": "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=480&h=320&fit=crop&q=80&seed=nmh"},

    # ── 목포 ──
    {"id": "MKP001", "name": "샹그리라 목포", "destination": "목포", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 3450,
     "address": "전남 목포시 평화로 81", "description": "유달산 뷰 목포 대표 호텔",
     "amenities": ["레스토랑", "주차", "카페", "피트니스"],
     "base_price": 100000, "image": "https://images.unsplash.com/photo-1549294413-26f195471e71?w=480&h=320&fit=crop&q=80&seed=mkp"},

    # ── 안동 ──
    {"id": "AND001", "name": "안동 그랜드호텔", "destination": "안동", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.0, "review_count": 2340,
     "address": "경북 안동시 경동로 743", "description": "하회마을 근처 전통 호텔",
     "amenities": ["레스토랑", "주차", "정원"],
     "base_price": 90000, "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=480&h=320&fit=crop&q=80&seed=and"},

    # ── 포항 ──
    {"id": "POH001", "name": "라한호텔 포항", "destination": "포항", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 3890,
     "address": "경북 포항시 북구 해안로 12", "description": "영일대해변 앞 오션뷰 호텔",
     "amenities": ["레스토랑", "주차", "오션뷰", "카페"],
     "base_price": 120000, "image": "https://images.unsplash.com/photo-1544124499-58912cbddaad?w=480&h=320&fit=crop&q=80&seed=poh"},

    # ── 순천 ──
    {"id": "SCN001", "name": "순천 가든호텔", "destination": "순천", "category": "domestic",
     "hotel_type": "hotel", "rating": 4.0, "review_count": 2890,
     "address": "전남 순천시 장명로 55", "description": "순천만 국가정원 근처 호텔",
     "amenities": ["레스토랑", "주차", "정원"],
     "base_price": 85000, "image": "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=480&h=320&fit=crop&q=80&seed=scn"},

    # ── 평창 ──
    {"id": "PCG001", "name": "알펜시아 리조트", "destination": "평창", "category": "domestic",
     "hotel_type": "resort", "rating": 4.3, "review_count": 8760,
     "address": "강원 평창군 대관령면 솔봉로 325", "description": "올림픽 시설 스키 리조트",
     "amenities": ["스키", "골프", "수영장", "레스토랑"],
     "base_price": 180000, "image": "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=480&h=320&fit=crop&q=80&seed=pcg"},
    {"id": "PCG002", "name": "용평리조트", "destination": "평창", "category": "domestic",
     "hotel_type": "resort", "rating": 4.2, "review_count": 12340,
     "address": "강원 평창군 대관령면 올림픽로 715", "description": "한국 최초 스키 리조트",
     "amenities": ["스키", "골프", "워터파크", "레스토랑"],
     "base_price": 150000, "image": "https://images.unsplash.com/photo-1585409677983-0f6c2e0b3ffd?w=480&h=320&fit=crop&q=80&seed=pcg2"},

    # ── 담양 ──
    {"id": "DMY001", "name": "담양 리조트 스파", "destination": "담양", "category": "domestic",
     "hotel_type": "resort", "rating": 4.1, "review_count": 3210,
     "address": "전남 담양군 금성면 금성로 882", "description": "대나무 숲 속 온천 리조트",
     "amenities": ["온천", "스파", "레스토랑", "정원"],
     "base_price": 130000, "image": "https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=480&h=320&fit=crop&q=80&seed=dmy"},

    # ══════════════════════════════════════════════
    #  해외 (International)
    # ══════════════════════════════════════════════

    # ── 도쿄 ──
    {"id": "TKY001", "name": "더 프린스 갤러리 도쿄", "destination": "도쿄", "category": "international",
     "hotel_type": "hotel", "rating": 4.7, "review_count": 6840,
     "address": "Kioicho 1-2, Chiyoda-ku, Tokyo", "description": "도쿄 중심 럭셔리 호텔, 도쿄타워 전망",
     "amenities": ["수영장", "스파", "레스토랑", "피트니스", "바"],
     "base_price": 380000, "image": "https://images.unsplash.com/photo-1542314831-de9b0a31f609?w=480&h=320&fit=crop&q=80&seed=tky1"},
    {"id": "TKY002", "name": "시부야 스트림 엑셀호텔 도큐", "destination": "도쿄", "category": "international",
     "hotel_type": "hotel", "rating": 4.3, "review_count": 9210,
     "address": "Shibuya 3-21-3, Shibuya-ku, Tokyo", "description": "시부야역 직결 모던 호텔",
     "amenities": ["레스토랑", "카페", "피트니스"],
     "base_price": 180000, "image": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=480&h=320&fit=crop&q=80&seed=tky2"},
    {"id": "TKY003", "name": "도쿄 스테이 신주쿠", "destination": "도쿄", "category": "international",
     "hotel_type": "hotel", "rating": 4.0, "review_count": 14320,
     "address": "Shinjuku 7-27-9, Shinjuku-ku, Tokyo", "description": "신주쿠역 도보 5분 가성비 호텔",
     "amenities": ["세탁", "와이파이", "주방"],
     "base_price": 95000, "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=480&h=320&fit=crop&q=80&seed=tky3"},
    {"id": "TKY004", "name": "호텔 그레이서리 신주쿠", "destination": "도쿄", "category": "international",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 11540,
     "address": "Kabukicho 1-19-1, Shinjuku-ku, Tokyo", "description": "가부키쵸 랜드마크, 고질라 호텔",
     "amenities": ["레스토랑", "카페", "와이파이"],
     "base_price": 120000, "image": "https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=480&h=320&fit=crop&q=80&seed=tky4"},

    # ── 오사카 ──
    {"id": "OSA001", "name": "스위스호텔 난카이 오사카", "destination": "오사카", "category": "international",
     "hotel_type": "hotel", "rating": 4.5, "review_count": 8970,
     "address": "Namba 5-1-60, Chuo-ku, Osaka", "description": "난바역 직결 프리미엄 호텔",
     "amenities": ["수영장", "피트니스", "스파", "레스토랑"],
     "base_price": 220000, "image": "https://images.unsplash.com/photo-1455587734955-081b22074882?w=480&h=320&fit=crop&q=80&seed=osa1"},
    {"id": "OSA002", "name": "크로스호텔 오사카", "destination": "오사카", "category": "international",
     "hotel_type": "hotel", "rating": 4.3, "review_count": 7650,
     "address": "Shinsaibashisuji 2-5-15, Chuo-ku, Osaka", "description": "신사이바시 중심 디자인 호텔",
     "amenities": ["레스토랑", "바", "피트니스"],
     "base_price": 140000, "image": "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=480&h=320&fit=crop&q=80&seed=osa2"},
    {"id": "OSA003", "name": "호텔 몬토레 그라스미어 오사카", "destination": "오사카", "category": "international",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 5430,
     "address": "Nanbanaka 2-2-2, Naniwa-ku, Osaka", "description": "난바 JR역 바로 앞",
     "amenities": ["레스토랑", "스파", "피트니스"],
     "base_price": 110000, "image": "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=480&h=320&fit=crop&q=80&seed=osa3"},

    # ── 방콕 ──
    {"id": "BKK001", "name": "만다린 오리엔탈 방콕", "destination": "방콕", "category": "international",
     "hotel_type": "hotel", "rating": 4.8, "review_count": 5120,
     "address": "48 Oriental Avenue, Bangkok", "description": "차오프라야강변 전설적 럭셔리 호텔",
     "amenities": ["수영장", "스파", "레스토랑", "리버뷰", "보트"],
     "base_price": 350000, "image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=480&h=320&fit=crop&q=80&seed=bkk1"},
    {"id": "BKK002", "name": "센타라 그랜드 앳 센트럴월드", "destination": "방콕", "category": "international",
     "hotel_type": "hotel", "rating": 4.4, "review_count": 9870,
     "address": "999/99 Rama 1 Road, Bangkok", "description": "센트럴월드 쇼핑몰 직결",
     "amenities": ["수영장", "피트니스", "스파", "레스토랑"],
     "base_price": 150000, "image": "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=480&h=320&fit=crop&q=80&seed=bkk2"},
    {"id": "BKK003", "name": "이비스 방콕 시암", "destination": "방콕", "category": "international",
     "hotel_type": "hotel", "rating": 3.9, "review_count": 16540,
     "address": "927 Rama 1 Road, Bangkok", "description": "시암역 도보 3분 가성비 최고",
     "amenities": ["레스토랑", "와이파이", "세탁"],
     "base_price": 55000, "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=480&h=320&fit=crop&q=80&seed=bkk3"},

    # ── 다낭 ──
    {"id": "DAN001", "name": "인터컨티넨탈 다낭 선 페닌슐라", "destination": "다낭", "category": "international",
     "hotel_type": "resort", "rating": 4.8, "review_count": 6780,
     "address": "Bai Bac, Son Tra, Da Nang", "description": "손트라 반도 초프리미엄 리조트",
     "amenities": ["수영장", "스파", "골프", "해변", "키즈클럽"],
     "base_price": 400000, "image": "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=480&h=320&fit=crop&q=80&seed=dan1"},
    {"id": "DAN002", "name": "하얏트 리젠시 다낭", "destination": "다낭", "category": "international",
     "hotel_type": "resort", "rating": 4.5, "review_count": 8340,
     "address": "5 Truong Sa, Hoa Hai, Da Nang", "description": "논느억 해변 5성급 리조트",
     "amenities": ["수영장", "스파", "레스토랑", "해변", "피트니스"],
     "base_price": 200000, "image": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=480&h=320&fit=crop&q=80&seed=dan2"},
    {"id": "DAN003", "name": "알라카르테 다낭 비치", "destination": "다낭", "category": "international",
     "hotel_type": "hotel", "rating": 4.2, "review_count": 11230,
     "address": "200 Vo Nguyen Giap, Da Nang", "description": "미케비치 앞 가성비 4성급",
     "amenities": ["수영장", "레스토랑", "해변", "피트니스"],
     "base_price": 90000, "image": "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=480&h=320&fit=crop&q=80&seed=dan3"},

    # ── 싱가포르 ──
    {"id": "SIN001", "name": "마리나베이 샌즈", "destination": "싱가포르", "category": "international",
     "hotel_type": "hotel", "rating": 4.6, "review_count": 18920,
     "address": "10 Bayfront Avenue, Singapore", "description": "싱가포르 랜드마크 인피니티풀 호텔",
     "amenities": ["인피니티풀", "카지노", "쇼핑", "레스토랑", "스파"],
     "base_price": 450000, "image": "https://images.unsplash.com/photo-1561501900-3701fa6a0864?w=480&h=320&fit=crop&q=80&seed=sin1"},
    {"id": "SIN002", "name": "칼튼호텔 싱가포르", "destination": "싱가포르", "category": "international",
     "hotel_type": "hotel", "rating": 4.3, "review_count": 7650,
     "address": "76 Bras Basah Road, Singapore", "description": "시티홀역 앞 비즈니스 호텔",
     "amenities": ["수영장", "피트니스", "레스토랑"],
     "base_price": 200000, "image": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=480&h=320&fit=crop&q=80&seed=sin2"},

    # ── 하와이 ──
    {"id": "HWI001", "name": "하얏트 리젠시 와이키키", "destination": "하와이", "category": "international",
     "hotel_type": "resort", "rating": 4.4, "review_count": 9870,
     "address": "2424 Kalakaua Ave, Honolulu", "description": "와이키키 비치 정면 트윈타워 리조트",
     "amenities": ["수영장", "스파", "해변", "레스토랑", "루아우"],
     "base_price": 350000, "image": "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=480&h=320&fit=crop&q=80&seed=hwi1"},

    # ── 파리 ──
    {"id": "PAR001", "name": "풀만 파리 투르 에펠", "destination": "파리", "category": "international",
     "hotel_type": "hotel", "rating": 4.3, "review_count": 6540,
     "address": "18 Avenue de Suffren, Paris", "description": "에펠탑 도보 5분 4성급 호텔",
     "amenities": ["레스토랑", "바", "피트니스", "주차"],
     "base_price": 280000, "image": "https://images.unsplash.com/photo-1551016043-93ae65f4c88c?w=480&h=320&fit=crop&q=80&seed=par1"},

    # ── 발리 ──
    {"id": "BAL001", "name": "더 물리아 발리", "destination": "발리", "category": "international",
     "hotel_type": "resort", "rating": 4.7, "review_count": 7890,
     "address": "Jl. Raya Nusa Dua Selatan, Bali", "description": "누사두아 최고급 올인클루시브 리조트",
     "amenities": ["수영장", "스파", "해변", "레스토랑", "키즈클럽"],
     "base_price": 280000, "image": "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=480&h=320&fit=crop&q=80&seed=bal1"},
    {"id": "BAL002", "name": "알리야 우붓", "destination": "발리", "category": "international",
     "hotel_type": "resort", "rating": 4.5, "review_count": 5430,
     "address": "Jl. Bisma, Ubud, Bali", "description": "우붓 열대림 속 풀빌라 리조트",
     "amenities": ["인피니티풀", "스파", "요가", "레스토랑"],
     "base_price": 200000, "image": "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=480&h=320&fit=crop&q=80&seed=bal2"},

    # ── 세부 ──
    {"id": "CEB001", "name": "샹그릴라 막탄 리조트 앤 스파", "destination": "세부", "category": "international",
     "hotel_type": "resort", "rating": 4.5, "review_count": 8760,
     "address": "Punta Engano Road, Cebu", "description": "막탄섬 대표 5성급 리조트",
     "amenities": ["수영장", "스파", "해변", "다이빙", "키즈클럽"],
     "base_price": 220000, "image": "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?w=480&h=320&fit=crop&q=80&seed=ceb1"},

    # ── 후쿠오카 ──
    {"id": "FUK001", "name": "그랜드 하얏트 후쿠오카", "destination": "후쿠오카", "category": "international",
     "hotel_type": "hotel", "rating": 4.4, "review_count": 6210,
     "address": "1-2-82 Sumiyoshi, Hakata-ku, Fukuoka", "description": "캐널시티 직결 프리미엄 호텔",
     "amenities": ["수영장", "스파", "피트니스", "레스토랑"],
     "base_price": 180000, "image": "https://images.unsplash.com/photo-1542314831-de9b0a31f609?w=480&h=320&fit=crop&q=80&seed=fuk1"},
    {"id": "FUK002", "name": "호텔 포르자 하카타역", "destination": "후쿠오카", "category": "international",
     "hotel_type": "hotel", "rating": 4.1, "review_count": 9870,
     "address": "Hakata Ekimae 2-1-1, Fukuoka", "description": "하카타역 바로 앞 가성비 호텔",
     "amenities": ["레스토랑", "세탁", "와이파이"],
     "base_price": 80000, "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=480&h=320&fit=crop&q=80&seed=fuk2"},

    # ── 타이베이 ──
    {"id": "TPE001", "name": "W 타이베이", "destination": "타이베이", "category": "international",
     "hotel_type": "hotel", "rating": 4.5, "review_count": 5670,
     "address": "No. 10, Zhongxiao E. Rd., Taipei", "description": "신이구 중심 트렌디 호텔",
     "amenities": ["수영장", "바", "피트니스", "레스토랑"],
     "base_price": 250000, "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=480&h=320&fit=crop&q=80&seed=tpe1"},

    # ── 홍콩 ──
    {"id": "HKG001", "name": "더 페닌슐라 홍콩", "destination": "홍콩", "category": "international",
     "hotel_type": "hotel", "rating": 4.8, "review_count": 4320,
     "address": "Salisbury Road, Kowloon, Hong Kong", "description": "침사추이 전설적 럭셔리 호텔",
     "amenities": ["수영장", "스파", "헬리패드", "레스토랑", "롤스로이스"],
     "base_price": 500000, "image": "https://images.unsplash.com/photo-1455587734955-081b22074882?w=480&h=320&fit=crop&q=80&seed=hkg1"},
]

OTA_PROVIDERS = [
    {"name": "야놀자", "logo_emoji": "Y", "color": "#FF3478"},
    {"name": "여기어때", "logo_emoji": "여", "color": "#FFC107"},
    {"name": "부킹닷컴", "logo_emoji": "B", "color": "#003580"},
    {"name": "아고다", "logo_emoji": "A", "color": "#5C2D91"},
    {"name": "호텔스닷컴", "logo_emoji": "H", "color": "#D32F2F"},
    {"name": "트립닷컴", "logo_emoji": "T", "color": "#287DFA"},
]
